#!/usr/bin/env ruby
# frozen_string_literal: true
require "rubygems"
require "thor"
require "et_full_system/cli"
module EtFullSystem
  class RootCommand < Thor
    desc "local command(s)", "Performs commands on a local server (non docker)"
    subcommand "local", LocalCommand


  end
end
EtFullSystem::RootCommand.start
