#!/usr/bin/env ruby
# frozen_string_literal: true
require "rubygems"
require "thor"
require "et_full_system"
require "et_full_system/cli"
require "et_full_system/version"
module EtFullSystem
  class RootCommand < Thor
    desc "local command(s)", "Performs commands on a local server (non docker)"
    subcommand "local", LocalCommand

    desc "docker command(s)", "Performs commands on a docker server"
    subcommand "docker", DockerCommand

    desc "workspace command(s)", "Performs commands on a et full system workspace"
    subcommand "workspace", WorkspaceCommand

    desc "version", "Shows the version of et_full_system"
    def version
      puts ::EtFullSystem::VERSION
    end

    map "--version": :version
  end
end
EtFullSystem::RootCommand.start
